# Generated by Django 2.0.7 on 2018-07-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='shoppinglist',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='description',
            field=models.CharField(default='desc', max_length=100),
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AddField(
            model_name='item',
            name='shoppinglist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglists.Shoppinglist'),
        ),
    ]
