# Generated by Django 2.0.7 on 2018-07-21 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglists', '0003_item_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
